class BadRequestError(Exception):...
class BadCredentialsError(Exception):...
class BadRoleError(Exception):...
class NotFoundError(Exception):...
class FiltersDateError(Exception):...
class DuplicatedFieldsError(Exception):...
class CodeError(Exception):...